// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ERC1155} from "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {EIP712} from "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/**
 * @title  PathtrickSBT
 * @author Pathtrick — Ketupat Team
 * @notice BEP-1155 Soulbound Token (SBT) for Pathtrick AI Career Coach certificates.
 *         Uses EIP-712 ECDSA Signatures for AI-graded minting.
 *
 *  Key design decisions
 *  ────────────────────
 *  • Non-transferable: SBT logic overrides `_update` to reject transfers.
 *  • User-Paid Minting: User pays a mint fee (BNB) directly. No Paymaster needed.
 *  • ECDSA Signature: AI Backend signs a message (EIP-712) proving the user passed.
 *  • Double-mint guard: one certificate per (user, courseId) pair.
 */
contract PathtrickSBT is ERC1155, Ownable2Step, EIP712 {
    using ECDSA for bytes32;

    // ─────────────────────────────────────────────────────────────────────────
    // State
    // ─────────────────────────────────────────────────────────────────────────

    uint256 public mintPrice = 0.005 ether;
    address public adminSigner;

    /// @dev hasCertificate[user][courseId] — double-mint guard.
    mapping(address => mapping(uint256 => bool)) public hasCertificate;
    mapping(address => mapping(uint256 => uint256)) public nonces;

    // EIP-712 TypeHash for Signature Verification
    // Struct: MintCertificate(address user,uint256 courseId,uint256 nonce,uint256 deadline)
    bytes32 public constant MINT_TYPEHASH =
        keccak256("MintCertificate(address user,uint256 courseId,uint256 nonce,uint256 deadline)");

    // ─────────────────────────────────────────────────────────────────────────
    // Custom errors
    // ─────────────────────────────────────────────────────────────────────────

    error SoulboundTokenNonTransferable();
    error AlreadyCertified(address user, uint256 courseId);
    error IncorrectMintFee();
    error InvalidSignature();
    error WithdrawFailed();
    error AdminSignerCannotBeOwner();
    error SignatureExpired();

    // ─────────────────────────────────────────────────────────────────────────
    // Events
    // ─────────────────────────────────────────────────────────────────────────

    event CertificateMinted(address indexed to, uint256 indexed courseId);
    event AdminSignerUpdated(address oldSigner, address newSigner);
    event MintPriceUpdated(uint256 oldPrice, uint256 newPrice);

    // ─────────────────────────────────────────────────────────────────────────
    // Constructor
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @param initialOwner Address that receives Ownable admin rights (for withdrawal/config).
     * @param _adminSigner Address of the Backend AI wallet that signs the certificates.
     * @param uri_         Metadata URI for the ERC1155 tokens.
     */
    constructor(address initialOwner, address _adminSigner, string memory uri_)
        ERC1155(uri_)
        Ownable(initialOwner)
        EIP712("PathtrickSBT", "1")
    {
        require(_adminSigner != address(0), "zero address");
        if (_adminSigner == initialOwner) {
            revert AdminSignerCannotBeOwner();
        }
        adminSigner = _adminSigner;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Mint
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice Mint a soulbound certificate after passing the AI grading.
     * @dev    User must pay `mintPrice` BNB and provide a valid EIP-712 signature
     *         from the `adminSigner`.
     *
     * @param courseId  Course / skill-path identifier (used as tokenId).
     * @param deadline Unix timestamp after which the signature is invalid.
     * @param signature ECDSA signature generated by Backend AI.
     */
    function mintCertificate(uint256 courseId, uint256 deadline, bytes calldata signature) external payable {
        // 1. Verify Payment
        if (msg.value != mintPrice) {
            revert IncorrectMintFee();
        }

        // 2. Double-mint guard (Replay Protection)
        if (hasCertificate[msg.sender][courseId]) {
            revert AlreadyCertified(msg.sender, courseId);
        }
        if (deadline < block.timestamp) {
            revert SignatureExpired();
        }

        uint256 nonce = nonces[msg.sender][courseId];

        // 3. Verify EIP-712 Signature
        bytes32 structHash = keccak256(abi.encode(MINT_TYPEHASH, msg.sender, courseId, nonce, deadline));
        bytes32 digest = _hashTypedDataV4(structHash);

        address recoveredSigner = digest.recover(signature);
        if (recoveredSigner != adminSigner || recoveredSigner == address(0)) {
            revert InvalidSignature();
        }

        // 4. Update state and mint
        nonces[msg.sender][courseId] = nonce + 1;
        hasCertificate[msg.sender][courseId] = true;
        _mint(msg.sender, courseId, 1, "");

        emit CertificateMinted(msg.sender, courseId);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Admin Functions
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice Withdraw collected BNB from mint fees.
     */
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        (bool success,) = owner().call{value: balance}("");
        if (!success) {
            revert WithdrawFailed();
        }
    }

    /**
     * @notice Update the admin signer address (e.g., key rotation).
     */
    function setAdminSigner(address _newSigner) external onlyOwner {
        address oldSigner = adminSigner;
        require(_newSigner != address(0), "zero address");
        if (_newSigner == owner()) {
            revert AdminSignerCannotBeOwner();
        }
        adminSigner = _newSigner;
        emit AdminSignerUpdated(oldSigner, _newSigner);
    }

    /**
     * @notice Update the mint fee.
     */
    function setMintPrice(uint256 _newPrice) external onlyOwner {
        uint256 oldPrice = mintPrice;
        mintPrice = _newPrice;
        emit MintPriceUpdated(oldPrice, _newPrice);
    }

    /**
     * @notice Update the token URI.
     */
    function setURI(string memory newuri) external onlyOwner {
        _setURI(newuri);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Soulbound overrides — block all transfers & approvals
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @dev OZ v5 routes all mint / burn / transfer flows through _update().
     *      We override it to reject any call where both from and to are non-zero
     *      (i.e., normal transfers).
     */
    function _update(address from, address to, uint256[] memory ids, uint256[] memory values)
        internal
        virtual
        override
    {
        // Allow minting (from == 0) and burning (to == 0)
        // Block transfers (from != 0 && to != 0)
        if (from != address(0) && to != address(0)) {
            revert SoulboundTokenNonTransferable();
        }

        super._update(from, to, ids, values);
    }

    /**
     * @dev Operator approvals are meaningless on an SBT — always revert to save user gas.
     */
    function setApprovalForAll(address, bool) public pure override {
        revert SoulboundTokenNonTransferable();
    }
}
